"""empty message

Revision ID: 08e9aba62fd5
Revises: 2e88b3d78263
Create Date: 2021-08-05 09:45:42.951016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08e9aba62fd5'
down_revision = '2e88b3d78263'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crane.t_CraneUserLoginHistory',
    sa.Column('UserLoginHistory_id', sa.Integer(), nullable=False),
    sa.Column('HistLogUser_id', sa.Integer(), nullable=False),
    sa.Column('LogStaff_id', sa.Integer(), nullable=True),
    sa.Column('CraneCompany_id', sa.Integer(), nullable=True),
    sa.Column('LogCompanyAuthorisedUser_id', sa.Integer(), nullable=True),
    sa.Column('LogAuthorisedUserName', sa.VARCHAR(length=100), nullable=True),
    sa.Column('LoginStatus_id', sa.Integer(), nullable=True),
    sa.Column('UserOnlineStatus', sa.SMALLINT(), nullable=True),
    sa.Column('LogLoginDate', sa.DateTime(), nullable=True),
    sa.Column('LogLogoutDate', sa.DateTime(), nullable=True),
    sa.Column('UserLoginLogName', sa.VARCHAR(length=100), nullable=True),
    sa.Column('UserAcessLogName', sa.VARCHAR(length=100), nullable=True),
    sa.Column('Comments', sa.NVARCHAR(length=500), nullable=True),
    sa.ForeignKeyConstraint(['HistLogUser_id'], ['crane.t_CraneUser.CraneUser_id'], ),
    sa.PrimaryKeyConstraint('UserLoginHistory_id')
    )
    op.create_table('crane.t_CoreCatalog',
    sa.Column('CoreCatalog_id', sa.Integer(), nullable=False),
    sa.Column('WellboreCore_id', sa.Integer(), nullable=False),
    sa.Column('CoreType', sa.Integer(), nullable=False),
    sa.Column('StoreIdentifier', sa.NVARCHAR(length=100), nullable=True),
    sa.Column('CatalogCoreFromDepth', sa.DECIMAL(), nullable=True),
    sa.Column('CatalogCoreToDepth', sa.DECIMAL(), nullable=True),
    sa.Column('CoreCatalogSecurityFlag_id', sa.Integer(), nullable=True),
    sa.Column('WasAnalysed_id', sa.Integer(), nullable=True),
    sa.Column('TopStratLitho_id', sa.Integer(), nullable=True),
    sa.Column('BottomStratLitho_id', sa.Integer(), nullable=True),
    sa.Column('CatalogueCorePictureName', sa.TEXT(), nullable=True),
    sa.Column('CataloguePictureSoftcopyPath', sa.TEXT(), nullable=True),
    sa.Column('CataloguePictureHyperlink', sa.TEXT(), nullable=True),
    sa.Column('CatPictureUploadDate', sa.DateTime(), nullable=True),
    sa.Column('CatalogueReportSoftcopyPath', sa.TEXT(), nullable=True),
    sa.Column('CatalogueReportHyperlink', sa.TEXT(), nullable=True),
    sa.Column('CatReportUploadDate', sa.DateTime(), nullable=True),
    sa.Column('CatalogReportFormat_id', sa.Integer(), nullable=True),
    sa.Column('CatalogReportFileSize', sa.DECIMAL(), nullable=True),
    sa.Column('CatalogReportSecurityGrade_id', sa.Integer(), nullable=True),
    sa.Column('CoreCatalogName', sa.NVARCHAR(length=100), nullable=True),
    sa.Column('Comments', sa.NVARCHAR(length=500), nullable=True),
    sa.Column('CreatedBy_id', sa.Integer(), nullable=False),
    sa.Column('DateCreated', sa.DateTime(), nullable=True),
    sa.Column('ModifiedOn', sa.DateTime(), nullable=True),
    sa.Column('ModifiedBy', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['BottomStratLitho_id'], ['crane.t_StratLithoUnit.StratLitho_id'], ),
    sa.ForeignKeyConstraint(['CatalogReportFormat_id'], ['crane.rt_FileFormat.FileFormat_id'], ),
    sa.ForeignKeyConstraint(['CatalogReportSecurityGrade_id'], ['crane.rt_FileSecurityGrade.FileSecurityGrade_id'], ),
    sa.ForeignKeyConstraint(['CoreCatalogSecurityFlag_id'], ['crane.rt_CatalogSecurityFlag.CatalogSecurityFlag_id'], ),
    sa.ForeignKeyConstraint(['CoreType'], ['crane.rt_CoreType.CoreType_id'], ),
    sa.ForeignKeyConstraint(['CreatedBy_id'], ['crane.t_CraneUser.CraneUser_id'], ),
    sa.ForeignKeyConstraint(['ModifiedBy'], ['crane.t_CraneUser.CraneUser_id'], ),
    sa.ForeignKeyConstraint(['TopStratLitho_id'], ['crane.t_StratLithoUnit.StratLitho_id'], ),
    sa.ForeignKeyConstraint(['WellboreCore_id'], ['crane.t_WellboreCore.WellboreCore_id'], ),
    sa.PrimaryKeyConstraint('CoreCatalog_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('crane.t_CoreCatalog')
    op.drop_table('crane.t_CraneUserLoginHistory')
    # ### end Alembic commands ###
