"""empty message

Revision ID: 19e12e7edbe0
Revises: 4ee63d7c8575
Create Date: 2021-07-09 21:02:39.271713

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '19e12e7edbe0'
down_revision = '4ee63d7c8575'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crane.rt_FileSecurityGrade', 'ModifiedOn')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crane.rt_FileSecurityGrade', sa.Column('ModifiedOn', mssql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
