"""empty message

Revision ID: 1ac6cdea44c1
Revises: bc6e98f363c6
Create Date: 2021-09-19 01:00:16.299349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ac6cdea44c1'
down_revision = 'bc6e98f363c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('File_id', sa.Integer(), nullable=False))
    op.drop_column('reports', 'Report_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('Report_id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False))
    op.drop_column('reports', 'File_id')
    # ### end Alembic commands ###
