"""empty message

Revision ID: 1b8eb8730585
Revises: 1ac6cdea44c1
Create Date: 2021-09-19 01:02:04.431741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b8eb8730585'
down_revision = '1ac6cdea44c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('File_id', sa.Integer(), nullable=False),
    sa.Column('Cores_id', sa.Integer(), nullable=True),
    sa.Column('Fluid_samples_id', sa.Integer(), nullable=True),
    sa.Column('Rock_samples_id', sa.Integer(), nullable=True),
    sa.Column('Report_type', sa.Enum('Cores', 'Fluid_Samples', 'Rock_Samples', name='reporttypeenum'), nullable=True),
    sa.Column('Report_path', sa.VARCHAR(length=500), nullable=True),
    sa.Column('Photograph_path', sa.VARCHAR(length=500), nullable=True),
    sa.Column('CreatedBy_id', sa.Integer(), nullable=False),
    sa.Column('DateCreated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['Cores_id'], ['cores.Core_sample_id'], ),
    sa.ForeignKeyConstraint(['CreatedBy_id'], ['crane_t_CraneUser.CraneUser_id'], ),
    sa.ForeignKeyConstraint(['Fluid_samples_id'], ['fluid_samples.Sample_id'], ),
    sa.ForeignKeyConstraint(['Rock_samples_id'], ['rock_samples.id'], ),
    sa.PrimaryKeyConstraint('File_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('files')
    # ### end Alembic commands ###
