"""empty message

Revision ID: 2cf1bcf49207
Revises: 4b4254c9e023
Create Date: 2021-07-09 21:10:21.093539

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '2cf1bcf49207'
down_revision = '4b4254c9e023'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crane.rt_FileFormat', 'ModifiedOn')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crane.rt_FileFormat', sa.Column('ModifiedOn', mssql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
