"""empty message

Revision ID: 2e88b3d78263
Revises: 9ba5c7c075b2
Create Date: 2021-07-09 21:25:25.085697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e88b3d78263'
down_revision = '9ba5c7c075b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crane.rt_CoreType', sa.Column('ModifiedOn', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crane.rt_CoreType', 'ModifiedOn')
    # ### end Alembic commands ###
