"""empty message

Revision ID: 4a1c7a33766e
Revises: d64797928591
Create Date: 2021-07-09 13:23:36.260986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a1c7a33766e'
down_revision = 'd64797928591'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crane.t_CraneUser', sa.Column('UserWebSecurityLevel_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'crane.t_CraneUser', 'crane.rt_CraneWebSecurityLevel', ['UserWebSecurityLevel_id'], ['WebSecurityLevel_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'crane.t_CraneUser', type_='foreignkey')
    op.drop_column('crane.t_CraneUser', 'UserWebSecurityLevel_id')
    # ### end Alembic commands ###
