"""empty message

Revision ID: 4b4254c9e023
Revises: 19e12e7edbe0
Create Date: 2021-07-09 21:03:05.392699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b4254c9e023'
down_revision = '19e12e7edbe0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crane.rt_FileSecurityGrade', sa.Column('ModifiedOn', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crane.rt_FileSecurityGrade', 'ModifiedOn')
    # ### end Alembic commands ###
