"""empty message

Revision ID: 51f28a4b02e3
Revises: 2cf1bcf49207
Create Date: 2021-07-09 21:10:35.398509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51f28a4b02e3'
down_revision = '2cf1bcf49207'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crane.rt_FileFormat', sa.Column('ModifiedOn', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crane.rt_FileFormat', 'ModifiedOn')
    # ### end Alembic commands ###
