"""empty message

Revision ID: 80fc920c05af
Revises: 5c28fc29fdfa
Create Date: 2021-07-09 14:11:53.608181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80fc920c05af'
down_revision = '5c28fc29fdfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crane.rt_CatalogSecurityFlag', sa.Column('ModifiedBy', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'crane.rt_CatalogSecurityFlag', 'crane.t_CraneUser', ['ModifiedBy'], ['CraneUser_id'])
    op.add_column('crane.rt_CoreType', sa.Column('ModifiedBy', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'crane.rt_CoreType', 'crane.t_CraneUser', ['ModifiedBy'], ['CraneUser_id'])
    op.add_column('crane.rt_FileFormat', sa.Column('ModifiedBy', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'crane.rt_FileFormat', 'crane.t_CraneUser', ['ModifiedBy'], ['CraneUser_id'])
    op.add_column('crane.rt_FileSecurityGrade', sa.Column('ModifiedBy', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'crane.rt_FileSecurityGrade', 'crane.t_CraneUser', ['ModifiedBy'], ['CraneUser_id'])
    op.add_column('crane.t_CraneUserLoginHistory', sa.Column('HistLogUser_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'crane.t_CraneUserLoginHistory', 'crane.t_CraneUser', ['HistLogUser_id'], ['CraneUser_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'crane.t_CraneUserLoginHistory', type_='foreignkey')
    op.drop_column('crane.t_CraneUserLoginHistory', 'HistLogUser_id')
    op.drop_constraint(None, 'crane.rt_FileSecurityGrade', type_='foreignkey')
    op.drop_column('crane.rt_FileSecurityGrade', 'ModifiedBy')
    op.drop_constraint(None, 'crane.rt_FileFormat', type_='foreignkey')
    op.drop_column('crane.rt_FileFormat', 'ModifiedBy')
    op.drop_constraint(None, 'crane.rt_CoreType', type_='foreignkey')
    op.drop_column('crane.rt_CoreType', 'ModifiedBy')
    op.drop_constraint(None, 'crane.rt_CatalogSecurityFlag', type_='foreignkey')
    op.drop_column('crane.rt_CatalogSecurityFlag', 'ModifiedBy')
    # ### end Alembic commands ###
