"""empty message

Revision ID: 8754db28c70e
Revises: d949ba9448f5
Create Date: 2021-11-24 00:24:00.050636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8754db28c70e'
down_revision = 'd949ba9448f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('geosims_t_FluidSamples', sa.Column('Sample_basin', sa.Enum('Edward-George', 'Semiliki', 'Pakwach', name='fluidsamplebasin'), nullable=True))
    op.add_column('geosims_t_RockSamples', sa.Column('Store_id', sa.VARCHAR(length=100), nullable=False))
    op.add_column('geosims_t_RockSamples', sa.Column('Sample_name', sa.VARCHAR(length=100), nullable=True))
    op.drop_column('geosims_t_RockSamples', 'Sample_id')
    op.drop_column('geosims_t_RockSamples', 'Rock_name')
    op.add_column('geosims_t_StratLithoUnit', sa.Column('LithoStratAge', sa.Enum('Early Pliocene', 'Early Miocene', 'Early Pleistocene', 'Holocene', 'Late Miocene', 'Late Pleistocene', 'Middle Miocene', 'Precambrian', name='lithoageenum'), nullable=True))
    op.drop_column('geosims_t_StratLithoUnit', 'LithoStratAge_id')
    op.drop_column('geosims_t_StratLithoUnit', 'ReserviorUnit')
    op.add_column('geosims_t_Wellbore', sa.Column('InitialWellborePurpose', sa.Enum('Wildcat', 'Appraisal', 'Production', 'Injection', 'Observation', name='purposeenum'), nullable=True))
    op.add_column('geosims_t_Wellbore', sa.Column('Wellbore_type', sa.Enum('Exploration', 'Development', name='wellboretypeenum'), nullable=True))
    op.add_column('geosims_t_Wellbore', sa.Column('OtherDevelopmentArea', sa.NVARCHAR(length=100), nullable=True))
    op.add_column('geosims_t_Wellbore', sa.Column('Basin', sa.Enum('Edward-George', 'Semiliki', 'Pakwach', name='fluidsamplebasin'), nullable=True))
    op.add_column('geosims_t_Wellbore', sa.Column('Discovery', sa.NVARCHAR(length=255), nullable=True))
    op.add_column('geosims_t_Wellbore', sa.Column('WellboreStatus', sa.Enum('Plugged and abandoned', 'Planned', 'Suspended', 'Withdrawn', 'In operation', 'In progress', name='statusenum'), nullable=True))
    op.drop_column('geosims_t_Wellbore', 'WellboreResponsibleLicence_id')
    op.drop_column('geosims_t_Wellbore', 'RCI_Taken_id')
    op.drop_column('geosims_t_Wellbore', 'Discovery_id')
    op.drop_column('geosims_t_Wellbore', 'WellboreStatus_id')
    op.drop_column('geosims_t_Wellbore', 'Well_id')
    op.drop_column('geosims_t_Wellbore', 'Basin_id')
    op.drop_column('geosims_t_Wellbore', 'InitialWellborePurpose_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('geosims_t_Wellbore', sa.Column('InitialWellborePurpose_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('geosims_t_Wellbore', sa.Column('Basin_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('geosims_t_Wellbore', sa.Column('Well_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('geosims_t_Wellbore', sa.Column('WellboreStatus_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('geosims_t_Wellbore', sa.Column('Discovery_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('geosims_t_Wellbore', sa.Column('RCI_Taken_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('geosims_t_Wellbore', sa.Column('WellboreResponsibleLicence_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('geosims_t_Wellbore', 'WellboreStatus')
    op.drop_column('geosims_t_Wellbore', 'Discovery')
    op.drop_column('geosims_t_Wellbore', 'Basin')
    op.drop_column('geosims_t_Wellbore', 'OtherDevelopmentArea')
    op.drop_column('geosims_t_Wellbore', 'Wellbore_type')
    op.drop_column('geosims_t_Wellbore', 'InitialWellborePurpose')
    op.add_column('geosims_t_StratLithoUnit', sa.Column('ReserviorUnit', sa.SMALLINT(), autoincrement=False, nullable=True))
    op.add_column('geosims_t_StratLithoUnit', sa.Column('LithoStratAge_id', sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.drop_column('geosims_t_StratLithoUnit', 'LithoStratAge')
    op.add_column('geosims_t_RockSamples', sa.Column('Rock_name', sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('geosims_t_RockSamples', sa.Column('Sample_id', sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False))
    op.drop_column('geosims_t_RockSamples', 'Sample_name')
    op.drop_column('geosims_t_RockSamples', 'Store_id')
    op.drop_column('geosims_t_FluidSamples', 'Sample_basin')
    # ### end Alembic commands ###
