"""empty message

Revision ID: 899c27c629b2
Revises: 1068796f4b64
Create Date: 2021-06-25 18:22:52.797455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '899c27c629b2'
down_revision = '1068796f4b64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crane.rt_CraneWebSecurityLevel',
    sa.Column('WebSecurityLevel_id', sa.Integer(), nullable=False),
    sa.Column('WebSecurityLevelName', sa.NVARCHAR(length=255), nullable=True),
    sa.Column('WebSecurityLevelDescription', sa.NVARCHAR(length=255), nullable=True),
    sa.Column('WebSecurityLevelAbbreviation', sa.NVARCHAR(length=255), nullable=True),
    sa.Column('Comments', sa.NVARCHAR(length=500), nullable=True),
    sa.Column('ModifiedOn', sa.DateTime(), nullable=True),
    sa.Column('ModifiedBy', sa.NVARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('WebSecurityLevel_id')
    )
    op.alter_column('crane.t_CraneUser', 'LoginErrorCount',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('crane.t_CraneUser', 'LoginStatus_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('crane.t_CraneUser', 'LoginStatus_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('crane.t_CraneUser', 'LoginErrorCount',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_table('crane.rt_CraneWebSecurityLevel')
    # ### end Alembic commands ###
