"""empty message

Revision ID: 8c2fb9dbf90b
Revises: 5b851931b3d8
Create Date: 2021-06-27 13:18:27.347430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c2fb9dbf90b'
down_revision = '5b851931b3d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crane.rt_CraneWebSecurityLevel',
    sa.Column('WebSecurityLevel_id', sa.Integer(), nullable=False),
    sa.Column('WebSecurityLevelName', sa.VARCHAR(length=255), nullable=True),
    sa.Column('WebSecurityLevelDescription', sa.VARCHAR(length=255), nullable=True),
    sa.Column('WebSecurityLevelAbbreviation', sa.VARCHAR(length=255), nullable=True),
    sa.Column('Comments', sa.VARCHAR(length=500), nullable=True),
    sa.Column('ModifiedOn', sa.DateTime(), nullable=True),
    sa.Column('ModifiedBy', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('WebSecurityLevel_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('crane.rt_CraneWebSecurityLevel')
    # ### end Alembic commands ###
