"""empty message

Revision ID: 9ba5c7c075b2
Revises: 51f28a4b02e3
Create Date: 2021-07-09 21:25:06.301234

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '9ba5c7c075b2'
down_revision = '51f28a4b02e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crane.rt_CoreType', 'ModifiedOn')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crane.rt_CoreType', sa.Column('ModifiedOn', mssql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
