"""empty message

Revision ID: a3f6f6dd4fd0
Revises: 8574c4ef5e4a
Create Date: 2022-03-04 14:56:38.157642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3f6f6dd4fd0'
down_revision = '8574c4ef5e4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('geosims_t_Company', sa.Column('DeleteStatus', sa.Enum('Deleted', 'Available', name='deletestatusenum'), nullable=True))
    op.add_column('geosims_t_CoreCatalog', sa.Column('DeleteStatus', sa.Enum('Deleted', 'Available', name='deletestatusenum'), nullable=True))
    op.add_column('geosims_t_Cores', sa.Column('DeleteStatus', sa.Enum('Deleted', 'Available', name='deletestatusenum'), nullable=True))
    op.add_column('geosims_t_CraneUser', sa.Column('DeleteStatus', sa.Enum('Deleted', 'Available', name='deletestatusenum'), nullable=True))
    op.add_column('geosims_t_CraneUserLoginHistory', sa.Column('DeleteStatus', sa.Enum('Deleted', 'Available', name='deletestatusenum'), nullable=True))
    op.add_column('geosims_t_Cuttings', sa.Column('DeleteStatus', sa.Enum('Deleted', 'Available', name='deletestatusenum'), nullable=True))
    op.add_column('geosims_t_FluidSamples', sa.Column('DeleteStatus', sa.Enum('Deleted', 'Available', name='deletestatusenum'), nullable=True))
    op.add_column('geosims_t_RockSamples', sa.Column('DeleteStatus', sa.Enum('Deleted', 'Available', name='deletestatusenum'), nullable=True))
    op.add_column('geosims_t_StratLithoUnit', sa.Column('DeleteStatus', sa.Enum('Deleted', 'Available', name='deletestatusenum'), nullable=True))
    op.add_column('geosims_t_Wellbore', sa.Column('DeleteStatus', sa.Enum('Deleted', 'Available', name='deletestatusenum'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('geosims_t_Wellbore', 'DeleteStatus')
    op.drop_column('geosims_t_StratLithoUnit', 'DeleteStatus')
    op.drop_column('geosims_t_RockSamples', 'DeleteStatus')
    op.drop_column('geosims_t_FluidSamples', 'DeleteStatus')
    op.drop_column('geosims_t_Cuttings', 'DeleteStatus')
    op.drop_column('geosims_t_CraneUserLoginHistory', 'DeleteStatus')
    op.drop_column('geosims_t_CraneUser', 'DeleteStatus')
    op.drop_column('geosims_t_Cores', 'DeleteStatus')
    op.drop_column('geosims_t_CoreCatalog', 'DeleteStatus')
    op.drop_column('geosims_t_Company', 'DeleteStatus')
    # ### end Alembic commands ###
