"""empty message

Revision ID: bc6e98f363c6
Revises: 33846e9636bb
Create Date: 2021-09-19 00:16:11.038752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc6e98f363c6'
down_revision = '33846e9636bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('Report_path', sa.VARCHAR(length=500), nullable=True))
    op.add_column('reports', sa.Column('Photograph_path', sa.VARCHAR(length=500), nullable=True))
    op.drop_column('reports', 'file_path')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('file_path', sa.VARCHAR(length=500, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.drop_column('reports', 'Photograph_path')
    op.drop_column('reports', 'Report_path')
    # ### end Alembic commands ###
