"""empty message

Revision ID: d949ba9448f5
Revises: 7e3d2a8bd140
Create Date: 2021-11-17 11:19:55.903575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd949ba9448f5'
down_revision = '7e3d2a8bd140'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('geosims_t_Company', sa.Column('Country', sa.String(), nullable=True))
    op.drop_column('geosims_t_Company', 'CountryOfOrigin_id')
    op.drop_column('geosims_t_Company', 'CountryOfRegistration_id')
    op.add_column('geosims_t_Cores', sa.Column('ReportFileFormat', sa.Enum('PDF', 'EXCEL', name='reportformatenum'), nullable=True))
    op.add_column('geosims_t_Cores', sa.Column('ReportSecurityGrade', sa.Enum('Restricted', 'Confidential', 'Open', name='securitygradeenum'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('geosims_t_Cores', 'ReportSecurityGrade')
    op.drop_column('geosims_t_Cores', 'ReportFileFormat')
    op.add_column('geosims_t_Company', sa.Column('CountryOfRegistration_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('geosims_t_Company', sa.Column('CountryOfOrigin_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('geosims_t_Company', 'Country')
    # ### end Alembic commands ###
