"""empty message

Revision ID: df4acd6dd23f
Revises: 1b8eb8730585
Create Date: 2021-09-19 14:46:30.864614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df4acd6dd23f'
down_revision = '1b8eb8730585'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cores', 'Core_number',
               existing_type=sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)
    op.alter_column('rock_samples', 'Rock_name',
               existing_type=sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rock_samples', 'Rock_name',
               existing_type=sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)
    op.alter_column('cores', 'Core_number',
               existing_type=sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
    # ### end Alembic commands ###
