"""empty message

Revision ID: df8ba0d9190e
Revises: 1e0ddc86ed10
Create Date: 2021-09-15 01:58:02.873623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df8ba0d9190e'
down_revision = '1e0ddc86ed10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crane_t_CraneUser', sa.Column('UserCategory', sa.Enum('App_Admin', 'Data_Admin', 'Staff', name='usercatgoryenum'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crane_t_CraneUser', 'UserCategory')
    # ### end Alembic commands ###
