"""empty message

Revision ID: e36f17cd32f9
Revises: 0c291934e450
Create Date: 2021-12-01 20:37:02.037659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e36f17cd32f9'
down_revision = '0c291934e450'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('geosims_t_CraneUser', sa.Column('ProfilePicture', sa.NVARCHAR(length=225), nullable=True))
    op.drop_column('geosims_t_Wellbore', 'SpudYear')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('geosims_t_Wellbore', sa.Column('SpudYear', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.drop_column('geosims_t_CraneUser', 'ProfilePicture')
    # ### end Alembic commands ###
