"""empty message

Revision ID: eed84689560f
Revises: a3f6f6dd4fd0
Create Date: 2022-03-21 01:32:22.981784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eed84689560f'
down_revision = 'a3f6f6dd4fd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('geosims_rt_CraneWebSecurityLevel', sa.Column('DeleteStatus', sa.Enum('Deleted', 'Available', name='deletestatusenum'), nullable=True))
    op.add_column('geosims_t_Company', sa.Column('CompanyType', sa.Enum('Licensing', 'Operator', name='companytypeenum'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('geosims_t_Company', 'CompanyType')
    op.drop_column('geosims_rt_CraneWebSecurityLevel', 'DeleteStatus')
    # ### end Alembic commands ###
