"""empty message

Revision ID: f2af16d7de43
Revises: 858c0886f374
Create Date: 2021-09-15 01:52:35.330569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2af16d7de43'
down_revision = '858c0886f374'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rock_samples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Sample_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('Date_collected', sa.DateTime(), nullable=True),
    sa.Column('Date_received', sa.DateTime(), nullable=True),
    sa.Column('Sample_basin', sa.Float(), nullable=True),
    sa.Column('Rock_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('Coordinate_location', sa.VARCHAR(length=100), nullable=True),
    sa.Column('Petrographic_description', sa.VARCHAR(length=500), nullable=True),
    sa.Column('Petrographic_analysis_reports', sa.VARCHAR(length=100), nullable=True),
    sa.Column('CreatedBy_id', sa.Integer(), nullable=False),
    sa.Column('DateCreated', sa.DateTime(), nullable=True),
    sa.Column('ModifiedOn', sa.DateTime(), nullable=True),
    sa.Column('ModifiedBy', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['CreatedBy_id'], ['crane_t_CraneUser.CraneUser_id'], ),
    sa.ForeignKeyConstraint(['ModifiedBy'], ['crane_t_CraneUser.CraneUser_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Rock_name'),
    sa.UniqueConstraint('Sample_id')
    )
    op.create_table('cores',
    sa.Column('Core_sample_id', sa.Integer(), nullable=False),
    sa.Column('Coring_contractor', sa.Integer(), nullable=True),
    sa.Column('Wellbore_id', sa.Integer(), nullable=True),
    sa.Column('Core_number', sa.VARCHAR(length=100), nullable=True),
    sa.Column('Coring_date', sa.DateTime(), nullable=True),
    sa.Column('Top_MD', sa.VARCHAR(length=100), nullable=True),
    sa.Column('Bottom_MD', sa.VARCHAR(length=100), nullable=True),
    sa.Column('Cut_length', sa.Integer(), nullable=True),
    sa.Column('Percentage_recovery', sa.Float(), nullable=True),
    sa.Column('Top_formation', sa.VARCHAR(length=100), nullable=True),
    sa.Column('Bottom_formation', sa.VARCHAR(length=100), nullable=True),
    sa.Column('Core_photograph', sa.VARCHAR(length=100), nullable=True),
    sa.Column('Core_analysis_reports', sa.VARCHAR(length=100), nullable=True),
    sa.Column('CreatedBy_id', sa.Integer(), nullable=False),
    sa.Column('DateCreated', sa.DateTime(), nullable=True),
    sa.Column('ModifiedOn', sa.DateTime(), nullable=True),
    sa.Column('ModifiedBy', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Coring_contractor'], ['crane_t_Company.Company_id'], ),
    sa.ForeignKeyConstraint(['CreatedBy_id'], ['crane_t_CraneUser.CraneUser_id'], ),
    sa.ForeignKeyConstraint(['ModifiedBy'], ['crane_t_CraneUser.CraneUser_id'], ),
    sa.ForeignKeyConstraint(['Wellbore_id'], ['crane_t_Wellbore.Wellbore_id'], ),
    sa.PrimaryKeyConstraint('Core_sample_id')
    )
    op.create_table('cuttings',
    sa.Column('Sample_id', sa.Integer(), nullable=False),
    sa.Column('Wellbore_id', sa.Integer(), nullable=True),
    sa.Column('Sample_box_number', sa.VARCHAR(length=100), nullable=True),
    sa.Column('Cutting_category', sa.Enum('Washed_Dried', 'Washed_Wet', 'Wet_Unwashed', 'Dry_Unwashed', name='cuttingscategoryenum'), nullable=False),
    sa.Column('Sample_type', sa.VARCHAR(length=100), nullable=True),
    sa.Column('Minimum_depth', sa.Float(), nullable=True),
    sa.Column('Maximum_depth', sa.Float(), nullable=True),
    sa.Column('Sample_interval', sa.VARCHAR(length=100), nullable=True),
    sa.Column('Date_received', sa.DateTime(), nullable=True),
    sa.Column('Other_description', sa.VARCHAR(length=500), nullable=True),
    sa.Column('CreatedBy_id', sa.Integer(), nullable=False),
    sa.Column('DateCreated', sa.DateTime(), nullable=True),
    sa.Column('ModifiedOn', sa.DateTime(), nullable=True),
    sa.Column('ModifiedBy', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['CreatedBy_id'], ['crane_t_CraneUser.CraneUser_id'], ),
    sa.ForeignKeyConstraint(['ModifiedBy'], ['crane_t_CraneUser.CraneUser_id'], ),
    sa.ForeignKeyConstraint(['Wellbore_id'], ['crane_t_Wellbore.Wellbore_id'], ),
    sa.PrimaryKeyConstraint('Sample_id')
    )
    op.create_table('fluid_samples',
    sa.Column('Sample_id', sa.Integer(), nullable=False),
    sa.Column('Wellbore_id', sa.Integer(), nullable=True),
    sa.Column('Sampling_activity', sa.VARCHAR(length=100), nullable=True),
    sa.Column('Fluid_category', sa.Enum('Oil', 'Gas', 'Water', name='fluidcategoryenum'), nullable=False),
    sa.Column('Sample_type', sa.VARCHAR(length=100), nullable=True),
    sa.Column('Sample_volume', sa.VARCHAR(length=100), nullable=True),
    sa.Column('Depth_obtained', sa.Float(), nullable=True),
    sa.Column('Date_collected', sa.DateTime(), nullable=True),
    sa.Column('Date_received', sa.DateTime(), nullable=True),
    sa.Column('Sampling_company', sa.Integer(), nullable=True),
    sa.Column('Analysis_reports', sa.VARCHAR(length=100), nullable=True),
    sa.Column('CreatedBy_id', sa.Integer(), nullable=False),
    sa.Column('DateCreated', sa.DateTime(), nullable=True),
    sa.Column('ModifiedOn', sa.DateTime(), nullable=True),
    sa.Column('ModifiedBy', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['CreatedBy_id'], ['crane_t_CraneUser.CraneUser_id'], ),
    sa.ForeignKeyConstraint(['ModifiedBy'], ['crane_t_CraneUser.CraneUser_id'], ),
    sa.ForeignKeyConstraint(['Sampling_company'], ['crane_t_Company.Company_id'], ),
    sa.ForeignKeyConstraint(['Wellbore_id'], ['crane_t_Wellbore.Wellbore_id'], ),
    sa.PrimaryKeyConstraint('Sample_id')
    )
    op.alter_column('crane_rt_CatalogSecurityFlag', 'CatalogSecurityFlagName',
               existing_type=sa.NVARCHAR(length=255),
               nullable=False)
    op.alter_column('crane_rt_CoreType', 'CoreTypeName',
               existing_type=sa.NVARCHAR(length=255),
               nullable=False)
    op.alter_column('crane_rt_CraneWebSecurityLevel', 'WebSecurityLevelName',
               existing_type=sa.NVARCHAR(length=255),
               nullable=False)
    op.alter_column('crane_rt_FileFormat', 'FileFormatName',
               existing_type=sa.NVARCHAR(length=255),
               nullable=False)
    op.alter_column('crane_rt_FileSecurityGrade', 'FileSecurityGradeName',
               existing_type=sa.NVARCHAR(length=255),
               nullable=False)
    op.alter_column('crane_t_CoreCatalog', 'CoreCatalogName',
               existing_type=sa.NVARCHAR(length=100),
               nullable=False)
    op.alter_column('crane_t_StratLithoUnit', 'StratLithoName',
               existing_type=sa.NVARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('crane_t_StratLithoUnit', 'StratLithoName',
               existing_type=sa.NVARCHAR(length=100),
               nullable=True)
    op.alter_column('crane_t_CoreCatalog', 'CoreCatalogName',
               existing_type=sa.NVARCHAR(length=100),
               nullable=True)
    op.alter_column('crane_rt_FileSecurityGrade', 'FileSecurityGradeName',
               existing_type=sa.NVARCHAR(length=255),
               nullable=True)
    op.alter_column('crane_rt_FileFormat', 'FileFormatName',
               existing_type=sa.NVARCHAR(length=255),
               nullable=True)
    op.alter_column('crane_rt_CraneWebSecurityLevel', 'WebSecurityLevelName',
               existing_type=sa.NVARCHAR(length=255),
               nullable=True)
    op.alter_column('crane_rt_CoreType', 'CoreTypeName',
               existing_type=sa.NVARCHAR(length=255),
               nullable=True)
    op.alter_column('crane_rt_CatalogSecurityFlag', 'CatalogSecurityFlagName',
               existing_type=sa.NVARCHAR(length=255),
               nullable=True)
    op.drop_table('fluid_samples')
    op.drop_table('cuttings')
    op.drop_table('cores')
    op.drop_table('rock_samples')
    # ### end Alembic commands ###
